### ISSUE TITLE
I'm confused by the rendering results on D-NeRF dataset between SC-GS and MaGS: SC-GS > MaGS? but not MaGS > SC-GS on D-NeRF dataset.

### ISSUE THREAD

**Issue by ywcmaike** [wcwac/MaGS#1]
Hi，I'm confused by the rendering results on D-NeRF dataset between SC-GS and MaGS. 

I have tried the code of SC-GS, which can reproduce the same rendering results on D-NeRF as described in the paper. Below are the original results of SC-GS. 
![sc-gs](https://github.com/wcwac/MaGS/assets/14950822/afdf960a-6855-4de1-9052-cc1430eb4607)

However, when I saw the MaGS paper, the rendering results of SC-GS are significantly lower than the psnr results of the original paper. Compared with the results of the original sc-gs paper, the performance of MaGS cannot exceed SC-GS at all. Below are the results of MaGS, which are not consistent with the original paper of SC-GS.
![mags](https://github.com/wcwac/MaGS/assets/14950822/d160011d-8818-4804-a5df-fdd44be1e24d)

Why do you highlight that MaGS is better than SC-GS? Is it over-claimed? Am I missing some key settings? Our recent work which will be submitted to Arxiv, is significantly better than MaGS and DGMesh. We hope to be able to make a fair comparison to promote the development of dynamic surface scenes. Could you please address my confusion?

**Comment by ywcmaike** [comment]
@wcwac

**Comment by wcwac** [comment]
Thank you for your question. May I ask what settings you used in your
comparison? The results provided in the sc-gs paper are all half-resolution
(400×400) tests, our paper provides both full-resolution and
half-resolution test results, where the half-resolution portion is
consistent with the scgs, which you can see in the appendix.

There are some algorithms where reducing the rendering resolution can
significantly improve metrics such as psnr, so we tested them separately.
In both settings our method achieved sota.


Weicai Ye 叶伟才 ***@***.***> 于 2024年6月11日周二 23:55写道：

**Comment by ywcmaike** [comment]
Thanks for your reply. It has solved my confusion. I'm sorry I do not see the appendix. Your results are consistent with our experiments. Despite the sota rendering results of mags, its surface is not generally unsatisfactory. 
left: ours , right: others
<img width="791" alt="52c49408-524d-4c86-9a0f-f16d5adfad02" src="https://github.com/wcwac/MaGS/assets/14950822/87bc0f98-9ba6-422c-aef9-8d38081c02c9">

upper: ours below: others
<img width="682" alt="381847b9-aaf7-462e-b85d-1a9d856de91f" src="https://github.com/wcwac/MaGS/assets/14950822/2909b862-0d9d-4664-ba24-87738bdbf8bf">

our baseline: still have little artifacts, final results: will submitted to arxiv soon.
![278_1718110115](https://github.com/wcwac/MaGS/assets/14950822/44355dc4-f14b-4064-b1db-0fccdf761006)
